services:
  function:
    container_name: function
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      FUNCTIONS: foo,bar
    volumes:
      - ../:/app
    restart: always
  foo:
    container_name: foo
    build:
      context: .
      dockerfile: foo/Dockerfile
    environment:
      FUNCTION_TARGET: Foo
    volumes:
      - ../:/app
    restart: always
  bar:
    container_name: bar
    build:
      context: .
      dockerfile: bar/Dockerfile
    environment:
      FUNCTION_TARGET: Bar
    volumes:
      - ../:/app
    restart: always
